### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by tudurom** [wmutils/libwm#5]
The last release was in 2015.

**Comment by z3bra** [comment]
Yeaaah I continued the development here actually: https://git.z3bra.org/libwm. Latest release is 1.2, which was tagged last year.

**Comment by tudurom** [comment]
Can you push the tags here on GitHub too please? The commits are up to date, but the tags are not.

**Comment by z3bra** [comment]
Should be done !

**Comment by tudurom** [comment]
Thanks!
